var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/";

MongoClient.connect(url, function(err, db) {
    if (err) throw err;
    var dbo = db.db("moviedb");
    var myobj = {
        name: "Part GmbH",
        confirmed: false,
        verified_by: "5706dcb2e69695f3096743af",
        organization: "60c859dbd47d0f0aa4727fcf",
    };

    var appointments = {
            title: "DeepL Exam",
            startDate: '2021-07-13T15:45',
            endDate: '2021-07-13T17:45',
            description: "Write an DeepL Exam",
            link: "Jitsi URL1",
            user: '60ecae1607bc0e63ac91e780',
            interests: ["Business and Industry"],
    }

    // source of facebook interests: https://interestexplorer.io/facebook-interests-list/

        var facebookInterestsCharacterLengthAdjusted = {
                facebookInterests:
                    ["Business",
                            "Advertising",
                            "Agriculture",
                            "Aviation",
                            "Banking",
                            "Investment",
                            "Design",
                            "Fashion",
                            "Graphic",
                            "Interior",
                            "Design",
                            "Economics",
                            "Engineering",
                            "Start-Ups",
                            "Health care",
                            "Education",
                            "Management",
                            "Marketing",
                            "Nursing",
                            "Online",
                            "Marketing",
                            "SEO",
                            "Social media",
                            "Web design",
                            "Web devel.",
                            "Finance",
                            "Insurance",
                            "Loans",
                            "Real estate",
                            "Retail",
                            "Sales",
                            "Science",
                            "Games",
                            "Gambling",
                            "Online games",
                            "Online poker",
                            "Video games",
                            "Racing games",
                            "RPGs",
                            "Shooter games",
                            "Strategy",
                            "Video games",
                            "Word games",
                            "Live events",
                            "Ballet",
                            "Bars",
                            "Concerts",
                            "Dancehalls",
                            "Festivals",
                            "Nightclubs",
                            "Parties",
                            "Plays",
                            "Theatre",
                            "Movies",
                            "Animes",
                            "Comedy",
                            "Documentaries",
                            "Fantasy",
                            "Horror",
                            "Musicals",
                            "Theater",
                            "Sci-Fi movies",
                            "Thrillers",
                            "Music",
                            "Blues",
                            "Classical",
                            "Country",
                            "Dance",
                            "Electronic",
                            "Gospel",
                            "Heavy metal",
                            "Hip hop",
                            "Jazz music",
                            "Music videos",
                            "Pop music",
                            "Reading",
                            "Books",
                            "Comics",
                            "E-books",
                            "Fiction books",
                            "Literature",
                            "Magazines",
                            "Manga",
                            "Mystery",
                            "Newspapers",
                            "Non-fiction",
                            "Novels",
                            "TV",
                            "TV comedies",
                            "Game shows",
                            "Reality shows",
                            "TV talkshows",
                            "Family",
                            "Relationships",
                            "Dating",
                            "Family",
                            "Fatherhood",
                            "Friendship",
                            "Marriage",
                            "Motherhood",
                            "Parenting",
                            "Weddings",
                            "Fitness",
                            "Wellness",
                            "Bodybuilding",
                            "Meditation",
                            "Exercise",
                            "Running",
                            "Weight lifting",
                            "Yoga",
                            "Food",
                            "Drinks",
                            "Alcohol",
                            "Beer",
                            "Wine",
                            "Beverages",
                            "Coffee",
                            "Energy drinks",
                            "Juice",
                            "Soft drinks",
                            "Tea",
                            "Cooking",
                            "Baking",
                            "Recipes",
                            "Cuisine",
                            "Chinese food",
                            "French food",
                            "German food",
                            "Greek food",
                            "Indian food",
                            "Spanish cuisine",
                            "Thai cuisine",
                            "Barbecue",
                            "Chocolate",
                            "Desserts",
                            "Fast food",
                            "Organic food",
                            "Pizza",
                            "Seafood",
                            "Vegan",
                            "Vegetarian",
                            "Paleo",
                            "Keto",
                            "Fasting",
                            "Diners",
                            "Arts",
                            "Acting",
                            "Crafts",
                            "Dance",
                            "Drawing",
                            "Drums",
                            "Fine art",
                            "Guitar",
                            "Painting",
                            "Photography",
                            "Sculpture",
                            "Singing",
                            "Writing",
                            "Current events",
                            "Gardening",
                            "DIY",
                            "Furniture",
                            "Gardening",
                            "Home",
                            "Pets",
                            "Birds",
                            "Cats",
                            "Dogs",
                            "Fish",
                            "Horses",
                            "Pet food",
                            "Rabbits",
                            "Reptiles",
                            "Law",
                            "Military",
                            "Politics",
                            "Religion",
                            "Sustainability",
                            "Veterans",
                            "Volunteering",
                            "Travel",
                            "Adventure",
                            "Air travel",
                            "Beaches",
                            "Car rentals",
                            "Cruises",
                            "Ecotourism",
                            "Hotels",
                            "Lakes",
                            "Mountains",
                            "Nature",
                            "Theme parks",
                            "Tourism",
                            "Vacations",
                            "Vehicles",
                            "Automobiles",
                            "Boats",
                            "Hybrids",
                            "Minivans",
                            "Motorcycles",
                            "RVs",
                            "SUVs",
                            "Scooters",
                            "Trucks",
                            "Shopping",
                            "Fashion",
                            "Beauty",
                            "Cosmetics",
                            "Fragrances",
                            "Hairs",
                            "Spas",
                            "Tattoos",
                            "Clothing",
                            "Shoes",
                            "Dresses",
                            "Handbags",
                            "Jewelry",
                            "Sunglasses",
                            "Shopping",
                            "Boutiques",
                            "Coupons",
                            "Toys",
                            "Sports",
                            "Ourdoors",
                            "Boating",
                            "Camping",
                            "Fishing",
                            "Hunting",
                            "Biking",
                            "Hiking",
                            "Surfing",
                            "Sports",
                            "Football",
                            "Soccer",
                            "Formel 1",
                            "Baseball",
                            "Basketball",
                            "Golf",
                            "Marathons",
                            "Skiing",
                            "Snowboarding",
                            "Swimming",
                            "Tennis",
                            "Thriathlons",
                            "Volleyball",
                            "Technology",
                            "Computers",
                            "Free software",
                            "Hard drives",
                            "Networking",
                            "Software",
                            "MERN",
                            "Tablets",
                            "Camcorders",
                            "Cameras",
                            "E-books",
                            "GPS devices",
                            "Game consoles",
                            "Mobile phones",
                            "Projectors",
                            "Smartphones",
                            "Televisions",
                    ],
        }

        // source icebreaker questions: https://museumhack.com/list-icebreakers-questions/#funny

    var icebreakerQuestions = {
        icebreakerQuestions:
            ["The zombie apocalypse is coming, who are 3 people you want on your team?",
                "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
                "If you were a wrestler what would be your entrance theme song?",
                "What did you name your first car?",
                "Does your current car have a name? What is it?",
                "You have your own late night talk show, who do you invite as your first guest?",
                "If a movie was made of your life what genre would it be, who would play you?",
                "If you were famous, what would you be famous for?",
                "You have to sing karaoke, what song do you pick?",
                "What was your least favorite food as a child? Do you still hate it or do you love it now?",
                "If you had to eat one meal everyday for the rest of your life what would it be?",
                "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?",
                "60s, 70s, 80s, 90s: Which decade do you love the most and why?",
                "What’s the best piece of advice you’ve ever been given?",
                "What is your favorite item you’ve bought this year?",
                "What is your favorite magical or mythological animal?",
                "Who is your favorite Disney hero or heroine? Would you trade places with them?",
                "If you could add anyone to Mount Rushmore who would it be; why?",
                "You’re going sail around the world, what’s the name of your boat?",
                "What fictional family would you be a member of?",
                "You can have an unlimited supply of one thing for the rest of your life, what is it? Sushi? Scotch Tape?",
                "Are you sunrise, daylight, twilight, or nighttime? Why?",
                "What fruit or vegetable would you most want to be?",
                "What is the strangest habit you have?",
                "What movie do you think everyone should watch?",
                "What is the last TV show that you binge-watched?",
                "What is one thing we would never guess about you?",
                "What current fact about your life would most impress your five year old self?",
            ],
    }

    dbo.collection("icebreaker questions").insertOne(icebreakerQuestions, function(err, res) {
        if (err) throw err;
        console.log("1 document inserted");
        db.close();
    });

    dbo.collection("appointments").insertOne(appointments, function(err, res) {
        if (err) throw err;
        console.log("1 document inserted");
        db.close();
    });

    dbo.collection("interests").insertOne(facebookInterestsCharacterLengthAdjusted, function(err, res) {
        if (err) throw err;
        console.log("1 document inserted");
        db.close();
    });

    {/*
      dbo.collection("organizations").insertOne(myobj, function(err, res) {
        if (err) throw err;
        console.log("1 document inserted");
        db.close();
    });
    */}
});